### ISSUE TITLE
How do i switch to 20.09 / unstable channel?

### ISSUE THREAD

**Issue by nazarewk** [Robertof/nixos-docker-sd-image-builder#17]
Hello,

I can't seem to find a way to switch to non-20.03 channel on built image, after switching to `nixos-unstable` branch in docker-compose i still end up with 20.03 named file and `nixos https://nixos.org/channels/nixos-20.03`.

How can i switch to at least 20.09 version?

**Comment by Robertof** [comment]
Hey!

You're absolutely right, I should point this to the stable 20.09 branch.

You just need to change this line:

https://github.com/Robertof/nixos-docker-sd-image-builder/blob/3a7f8dbd4955ebd9befe5b91be1ad1e8084b5618/docker/docker-compose.yml#L17

Just put `release-20.09` or `master` to get unstable, and then run `./run.sh up --build` to get some fresh containers. Hope that makes sense!

If you have time feel free to make a PR to change the built version to 20.09, I'd appreciate it!

**Comment by nazarewk** [comment]
I supposedly have it on `nixos-unstable` (i prefer this one so at least
builds of whole repo is passing), is it expected to have resulting image
with 20.03 channel set up in this case?

**Comment by nazarewk** [comment]
looks like i missed something on the way, running `docker system prune -a` then `run.sh up --build` seems to have kicked in different system version (i'm getting `error: The option `services.sshd.enabled' does not exist.` suggesting it's using different system version).

**Comment by nazarewk** [comment]
Nevermind, `nixos-unstable` actually builds 20.03 installer as seen in https://hydra.nixos.org/job/nixos/trunk-combined/nixos.sd_image.aarch64-linux

**Comment by Robertof** [comment]
Morning!

Yeah, the container needs to be recreated to update the version -- this is because `nixpkgs` are only cloned once when you create the container. Perhaps the `--force-recreate` option should help as well, like `./run.sh up --build --force-recreaet`.

You should actually get a 21.03pre from `nixos-unstable` from what I'm seeing:

https://github.com/NixOS/nixpkgs/blob/24c9b05ac53e422f1af81a156f1fd58499eb27fb/.version#L1

The error you described is quite interesting though. I can still see the `services.sshd.enabled` alias:
https://github.com/NixOS/nixpkgs/blob/24c9b05ac53e422f1af81a156f1fd58499eb27fb/nixos/modules/services/networking/ssh/sshd.nix#L78

Thanks!

**Comment by nazarewk** [comment]
@Robertof the code has `enable`, but your installer configuration has `enabled`

**Comment by Robertof** [comment]
Oh boi, you're correct. I wonder why this only surfaced now!? Need to fix it!
