### ISSUE TITLE
Unrealistic build times on readme

### ISSUE THREAD

**Issue by RusticCraftsman** [Robertof/nixos-docker-sd-image-builder#33]
On the readme you say:
> This repository allows you to build a custom SD image of NixOS for your Raspberry Pi (or any other supported AArch64 device) in about 15-20 minutes on a modern x86_64 system or about 5 minutes on a powerful AArch64 box, without installing any additional dependencies.

I built my iso in what i would kind of consider a ` modern x64_64 system ` , cpu being ` Intel i7-8750H (12) @ 4.100GHz ` and the build process took about 15 hours and 30 minutes, i was not expecting those times at all, maybe 2 hours at most. 
If these are the real times that are the common case we should change the expected time provided by the readme to adjust expectations , if this is an abnormality, let me know which information should i pass in order to start fixing this undesired behaviour.

**Comment by Robertof** [comment]
Hi! 15 hours is definitely not normal -- the build times in the README were measured by me personally at the time when I built the repo. Nowadays, I mostly build on aarch64, so it's possible that something is seriously wrong, perhaps on the QEMU side.

I'll try this out on an x86_64 machine and report back.

**Comment by Robertof** [comment]
Ah, I think I found the likely cause. By default, this repo points to the `release-23.11` branch of `nixpkgs` which contains _every_ latest change.

The problem is that this includes changes which haven't been picked up by Hydra yet (Nix's CI), and thus are not cached on `cache.nixos.org` (requiring a build from source). This is especially painful when very large packages such as the Linux kernel are updated: the lack of a cached derivation means that a full build must be performed, which takes ages via emulation.

The solution is switch to the "release channel" branch, which is prefixed with `nixos-` instead of `release-`. This kind of branch is guaranteed to have been already been built by Hydra, and thus to have every derivation cached. You can [clearly see](https://github.com/NixOS/nixpkgs/tree/nixos-23.11) that the `nixos-23.11` branch lags by 2 days compared to `release-23.11`. I have confirmed that using this branch on a x86_64 system builds snappily.

I'll change the default branch to `nixos-23.11` now so that this won't happen again. Thank you for your report!
